name: CI
on:
  push:
    branches:
      - master
      - feature
  pull_request:
    branches:
      - master
      - feature
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
